---
title: "R programming (r4ds Section III)"
author: "name"
date: "date"
output: 
  html_document: 
    keep_md: yes
---

# Ch 18: Pipes

_Demonstrate the use of the regular pipe (`%>%`) and the "explosion" operator (`%$%`) in some example_

```{r}
library(magrittr)
nums = c(1,2,3,4,5,6,7,8,9) %>% matrix(ncol = 3) %>% data.frame()

wtb = nums %$% table(X1,X2,X3)
```


----

# Ch 19: Functions

### 19.2: When should you write a function?
Answer any 3
```{r}
rescale01 <- function(x) {
  rng <- range(x, na.rm = TRUE)
  (x - rng[1]) / (rng[2] - rng[1])
}
rescale01(c(0, 5, 10))
rescale01(c(1, 2, 3, NA, 5))
```
1. If na.rm = FALSE, then all the max's and mins become na. 

3. 
```{r}
meanfun = function(x){
  c(mean(is.na(x)))
}

anotherfun = function(x){
  c(x / sum(x, na.rm = TRUE))
}

sdmean = function(x){
  c(sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE))
}
```

6. 
```{r}
setwd("C:/Users/mitch2/Documents/School/499/assignments-mborgert")
is_directory <- function(x) file.info(x)$isdir
```
This tells you whether a file is a directory.

```{r}
is_readable <- function(x) file.access(x, 4) == 0
?file.access
```
This is a function to test if a file is readable.

_Describe one time where you wish you had written a function, but didn't._
For a project in Math 458. It took way too much copying and pasting. 


### 19.3: Functions are for humans and computers

1.
```{r}
contains_prefix <- function(string, prefix) {
  substr(string, 1, nchar(prefix)) == prefix
}

contains_prefix("prefix","pre")
```
This says if a prefix is in a word. 

```{r}
final_number_remover <- function(x) {
  if (length(x) <= 1) return(NULL)
  x[-length(x)]
}

final_number_remover(c(1,2,3,4))
```
This removes the final number in a vector, if there is 1 number or less it returns null.

```{r}
f3 <- function(x, y) {
  rep(y, length.out = length(x))
}
```



_What does "Functions are for humans and computers" mean to you?_

### 19.4 Conditional execution
Answer any 3

### 19.5 Function arguments
Answer any 2

### 19.6: Return values
_Is it mandatory that you `return()` a value from a function? If not, give on reasons for why you would want to do so. If so, explain what happens if you don't include the return._

### 19.7: Environment
_What's the problem with the example function at the beginning of this chapter?_

----

# 20: Vectors

###  20.3: Important types of atomic vector
Answer any 2

### 20.4: Using Atomic Vectors
Answer #4, and then 2 others. 

### 20.5: Recursive vectors (lists)
Answer either one

### 20.7: Augmented vectors

_Describe at least two differences between a `data.frame` and a `tibble`_

----

# Chapter 21: Iteration

### 21.2: For Loops
Any one question

### 21.3: For Loop Variations
Problem #1

### 21.4: For loops vs functionals
Problem #2

### 21.5: the map function
Any 2 problems

----

End here. The rest of 21 is for your info only

